name: python
on:
  push:
    branches:
      - master
jobs:
  manylinux_x86_64:
    name: manylinux_x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./build.bash setup
      - run: sudo ./build.bash python
      - run: sudo -E ./build.bash release
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  manylinux_aarch64:
    name: manylinux_aarch64
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./build.bash setup
      - run: sudo ./build.bash python
      - run: sudo -E ./build.bash release
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  # musllinux_x86_64:
  #   name: musllinux_x86_64
  #   runs-on: ubuntu-latest
  #   container:
  #     image: phuslu/seashell:latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: bash ./build.bash setup
  #     - run: bash ./build.bash python
  #     - run: bash ./build.bash release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
  win_amd64:
    name: win_amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./build.bash setup
      - run: sudo ./build.bash python::windows
      - run: sudo -E ./build.bash release
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  win_arm64:
    name: win_arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./build.bash setup
      - run: sudo GOARCH=arm64 ./build.bash python::windows
      - run: sudo -E ./build.bash release
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
